# Borůvka minimum spanning forest (PySpark)

This notebook runs the same pipeline as `run_mst.py`: load graph text files under `data/`, execute Borůvka’s algorithm on Spark RDDs, and inspect the MSF/MST. Each section also writes results under the project `output/` folder (same format as the CLI). After the Spark run, a **Kruskal validation** step compares `total_weight`, `num_components`, and `|MST|` to a driver-side reference (see §“Validation”).

**Prerequisites:** a JDK, `pip install -r requirements.txt`, and a Jupyter environment (`pip install jupyter ipykernel`).

Set the kernel’s **working directory** to this project folder, or keep the default cells below—they locate the repo by searching for `src/boruvka_spark.py`.

In [1]:
# pip install -r requirements.txt

In [2]:
import os
import sys
from pathlib import Path

# Resolve project root whether the kernel cwd is the repo or a subfolder (e.g. notebooks/).
_candidates = [Path.cwd(), *Path.cwd().parents]
PROJ_ROOT = next(
    (p for p in _candidates if (p / "src" / "boruvka_spark.py").exists()),
    Path.cwd(),
)
sys.path.insert(0, str(PROJ_ROOT))
os.chdir(PROJ_ROOT)
print("PROJ_ROOT =", PROJ_ROOT.resolve())

PROJ_ROOT = /Users/kentpun/Documents/_04.studies/MSc BDT/MSBD 5003/_05. Project/Implementation

In [3]:
from pyspark.sql import SparkSession

from src.boruvka_spark import BoruvkaResult, boruvka_mst, run_boruvka_from_file
from src.mst_output import write_mst_file

spark = (
    SparkSession.builder.appName("BoruvkaMST-Notebook")
    .master(os.environ.get("SPARK_MASTER", "local[*]"))
    .getOrCreate()
)
sc = spark.sparkContext
sc.setLogLevel("WARN")
print("Spark ready")

26/04/21 22:14:03 WARN Utils: Your hostname, Kents-MacBook-Pro-2.local resolves to a loopback address: 127.0.0.1; using 10.79.83.227 instead (on interface en0)
26/04/21 22:14:03 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/21 22:14:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Spark ready

## Validation (Kruskal reference)

The next cell defines `validate_vs_kruskal`, which loads the same graph as Spark (or takes an explicit edge list), runs **Kruskal** on the driver, and checks `total_weight`, `num_components`, and `|MST|`. MST edge *sets* can differ when weights tie; those three checks still certify a correct MSF weight and structure.

In [4]:
import math

from src.graph_loader import load_graph_from_text
from src.mst_reference import kruskal_msf


def print_result_summary(name: str, boruvka_res: BoruvkaResult) -> None:
    print(f"[{name}] total_weight={boruvka_res.total_weight}")
    print(f"[{name}] num_iterations={boruvka_res.num_iterations}")
    print(f"[{name}] num_components={boruvka_res.num_components}")
    print(f"[{name}] mst_edge_count={len(boruvka_res.mst_edges)}")


def validate_vs_kruskal(
    boruvka_res: BoruvkaResult,
    *,
    edges_path: Path | None = None,
    fmt: str = "edge_list",
    edges: list[tuple[int, int, int | float]] | None = None,
    name: str = "graph",
    atol: float = 1e-6,
) -> None:
    if edges is not None:
        e = edges
    elif edges_path is not None:
        e = load_graph_from_text(
            edges_path.read_text(encoding="utf-8"), fmt=fmt
        )
    else:
        raise ValueError("Provide edges_path or edges=")

    ref_w, ref_mst, ref_comp = kruskal_msf(e)
    assert math.isclose(float(boruvka_res.total_weight), float(ref_w), rel_tol=0.0, abs_tol=atol), (
        f"{name}: total_weight spark={boruvka_res.total_weight} kruskal={ref_w} (atol={atol})"
    )
    assert boruvka_res.num_components == ref_comp, (
        f"{name}: components spark={boruvka_res.num_components} kruskal={ref_comp}"
    )
    assert len(boruvka_res.mst_edges) == len(ref_mst), (
        f"{name}: |MST| spark={len(boruvka_res.mst_edges)} kruskal={len(ref_mst)}"
    )
    print(
        f"✓ {name}: Kruskal agrees — weight={ref_w}, components={ref_comp}, |MST|={len(ref_mst)}"
    )

## 1. Edge list (`data/sample_edges.txt`)

Triangle graph: expect MST edges `(0,1,1)` and `(1,2,2)`, total weight `3`.

In [4]:
# For small demo, use sample_edges.txt; for large test, switch to hongkong_edges.txt.
# edge_path = PROJ_ROOT / "data" / "sample_edges.txt"
edge_path = PROJ_ROOT / "data" / "hongkong_edges.txt"

res = run_boruvka_from_file(sc, str(edge_path), fmt="edge_list")
out_path = write_mst_file(
    res,
    PROJ_ROOT / "output" / f"mst_{edge_path.stem}.txt",
    source=str(edge_path),
)
print("Wrote", out_path)
print_result_summary("§1", res)

# Kruskal validation is fine for small graphs. Skip it for very large graphs.
if edge_path.name != "hongkong_edges.txt":
    validate_vs_kruskal(res, edges_path=edge_path, fmt="edge_list", name="§1 sample_edges")
else:
    print("(skip Kruskal validation for hongkong_edges.txt in notebook)")

26/04/17 17:17:57 WARN GarbageCollectionMetrics: To enable non-built-in garbage collector(s) List(G1 Concurrent GC), users should configure it(them) to spark.eventLog.gcMetrics.youngGenerationGarbageCollectors or spark.eventLog.gcMetrics.oldGenerationGarbageCollectors

Wrote /Users/kentpun/Documents/_04.studies/MSc BDT/MSBD 5003/_05. Project/Implementation/output/mst_hongkong_edges.txt
[§1] total_weight=12710002.849999625
[§1] num_iterations=10
[§1] num_components=2149
[§1] mst_edge_count=1090744
(skip Kruskal validation for hongkong_edges.txt in notebook)

In [5]:
# Optional explicit check (can be expensive on very large files).
# Uses tolerance to avoid float representation noise.
validate_vs_kruskal(
    res,
    edges_path=edge_path,
    fmt="edge_list",
    name="§1 explicit check",
    atol=1e-4,
)

AssertionError: §1 sample_edges: total_weight spark=12710002.849999625 kruskal=12710002.85

### MST as a table

In [14]:
import pandas as pd

pd.DataFrame(res.mst_edges, columns=["u", "v", "weight"]).head(20)

   u  v  weight
0  0  1       1
1  1  2       2

## 2. Build an RDD (`boruvka_mst`)

Same as the CLI, this constructs `edges_rdd` from any source instead of a file.

In [15]:
inline_edges = [(0, 1, 4), (0, 2, 8), (1, 2, 2), (1, 3, 6), (2, 3, 3)]
edges_rdd = sc.parallelize(inline_edges)
res2 = boruvka_mst(sc, edges_rdd)
write_mst_file(res2, PROJ_ROOT / "output" / "mst_inline_example.txt", source="sc.parallelize(...)")
validate_vs_kruskal(res2, edges=inline_edges, name="§2 inline RDD")
pd.DataFrame(res2.mst_edges, columns=["u", "v", "weight"])

✓ §2 inline RDD: Kruskal agrees — weight=9, components=1, |MST|=3

   u  v  weight
0  0  1       4
1  1  2       2
2  2  3       3

## 3. Adjacency list file

`data/sample_adjacency.txt` — same triangle as §1.

In [17]:
adj_path = PROJ_ROOT / "data" / "sample_adjacency.txt"
res_adj = run_boruvka_from_file(sc, str(adj_path), fmt="adjacency_list")
write_mst_file(res_adj, PROJ_ROOT / "output" / "mst_sample_adjacency.txt", source=str(adj_path))
validate_vs_kruskal(
    res_adj, edges_path=adj_path, fmt="adjacency_list", name="§3 sample_adjacency"
)
pd.DataFrame(res_adj.mst_edges, columns=["u", "v", "weight"])

✓ §3 sample_adjacency: Kruskal agrees — weight=3, components=1, |MST|=2

   u  v  weight
0  0  1       1
1  1  2       2

## 4. Disconnected graph (minimum spanning *forest*)

`data/sample_disconnected.txt` — two components, `num_components == 2`.

In [18]:
disc_path = PROJ_ROOT / "data" / "sample_disconnected.txt"
res_disc = run_boruvka_from_file(sc, str(disc_path), fmt="edge_list")
write_mst_file(res_disc, PROJ_ROOT / "output" / "mst_sample_disconnected.txt", source=str(disc_path))
print("edges:", res_disc.mst_edges, "weight:", res_disc.total_weight, "components:", res_disc.num_components)
validate_vs_kruskal(res_disc, edges_path=disc_path, fmt="edge_list", name="§4 disconnected")
pd.DataFrame(res_disc.mst_edges, columns=["u", "v", "weight"])

edges: [(0, 1, 5), (2, 3, 7)] weight: 12 components: 2
✓ §4 disconnected: Kruskal agrees — weight=12, components=2, |MST|=2

   u  v  weight
0  0  1       5
1  2  3       7

## 5. Larger graph (`data/complex_random.txt`)

~120 vertices, ~620 edges. Kruskal validation plus optional cross-check against `data/complex_random.meta`.

In [19]:
complex_path = PROJ_ROOT / "data" / "complex_random.txt"
meta_path = PROJ_ROOT / "data" / "complex_random.meta"

res_big = run_boruvka_from_file(sc, str(complex_path), fmt="edge_list")
write_mst_file(res_big, PROJ_ROOT / "output" / "mst_complex_random.txt", source=str(complex_path))
print_result_summary("§5", res_big)
validate_vs_kruskal(
    res_big, edges_path=complex_path, fmt="edge_list", name="§5 complex_random"
)

if meta_path.exists():
    meta: dict[str, int] = {}
    for line in meta_path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split(maxsplit=1)
        if len(parts) != 2:
            continue
        key, val = parts
        if key in (
            "reference_total_weight",
            "reference_components",
            "reference_mst_edges",
        ):
            meta[key] = int(val)
    assert res_big.total_weight == meta["reference_total_weight"]
    print(
        "✓ matches complex_random.meta:",
        meta["reference_total_weight"],
        "weight,",
        meta["reference_components"],
        "components,",
        meta["reference_mst_edges"],
        "MST edges",
    )
else:
    print("(no complex_random.meta — skip file cross-check)")

pd.DataFrame(res_big.mst_edges, columns=["u", "v", "weight"]).head(10)

✓ §5 complex_random: Kruskal agrees — weight=752852, components=1, |MST|=119
✓ matches complex_random.meta: 752852 weight, 1 components, 119 MST edges

   u    v  weight
0  0   42    8574
1  0   44   11889
2  1   14    4932
3  1   92    9448
4  2   42    2059
5  2  101    6099
6  3   18    3029
7  3   82    3987
8  4   37   15171
9  4   58    5772

## 6. Distributed component merge demo (no driver union-find)

This demonstrates the practical distributed pattern from `src/distributed_component_merge.py`: emit component links, reconcile globally by iterative min-label propagation, then relabel `(vertex, component)` assignments.

For MST-level verification, use `validate_vs_kruskal(...)` above (now tolerance-aware for float weights).

In [5]:
from src.distributed_component_merge import relabel_components_distributed

# Synthetic (vertex -> current_component)
components_demo = sc.parallelize(
    [
        (0, 10),
        (1, 10),
        (2, 20),
        (3, 20),
        (4, 30),
        (5, 40),
    ]
)

# Proposed merges discovered in one Boruvka round (component-level links)
merge_pairs_demo = sc.parallelize(
    [
        (10, 20),
        (20, 30),
        (40, 40),  # self-link ignored by the function
    ]
)

relabeled_demo = relabel_components_distributed(
    components_demo,
    merge_pairs_demo,
    max_iterations=20,
)

print("Before:", sorted(components_demo.collect()))
print("After :", sorted(relabeled_demo.collect()))

# Expected: components 10/20/30 collapse to one root label (10); 40 stays 40.

Before: [(0, 10), (1, 10), (2, 20), (3, 20), (4, 30), (5, 40)]

After : [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 40)]

## 7. Validate distributed component relabel vs Kruskal

This runs an experimental Borůvka variant that uses `relabel_components_distributed(...)` for component contraction, then compares its MST/MSF result to Kruskal using the same `validate_vs_kruskal(...)` helper.

In [6]:
from src.distributed_component_merge import relabel_components_distributed
from src.graph_loader import Weight
from src.union_find import UnionFind


def boruvka_mst_distributed_relabel(sc, edges_rdd, max_iterations=None):
    """Experimental Boruvka: distributed component relabel, driver cycle-scan per round."""

    def norm_edge(u, v, w):
        a, b = (u, v) if u <= v else (v, u)
        return (a, b, w)

    def min_choice(a, b):
        return a if a <= b else b

    edges = (
        edges_rdd.map(lambda e: norm_edge(int(e[0]), int(e[1]), e[2]))
        .filter(lambda e: e[0] != e[1])
        .distinct()
        .cache()
    )

    vertices = edges.flatMap(lambda e: (e[0], e[1])).distinct().cache()
    n_vertices = vertices.count()
    if n_vertices == 0:
        return BoruvkaResult([], 0, 0, 0)

    components = vertices.map(lambda v: (v, v)).cache()
    mst_acc = []
    iters = 0
    cap = max_iterations if max_iterations is not None else n_vertices

    try:
        while iters < cap:
            comp_by_v = components

            e_u = edges.map(lambda e: (e[0], (e[1], e[2]))).join(comp_by_v)
            keyed_by_v = e_u.map(lambda x: (x[1][0][0], (x[0], x[1][0][1], x[1][1])))
            joined = keyed_by_v.join(comp_by_v).map(
                lambda x: (x[1][0][0], x[0], x[1][0][1], x[1][0][2], x[1][1])
            )

            cross = joined.filter(lambda t: t[3] != t[4])
            if cross.isEmpty():
                break

            candidates = cross.flatMap(
                lambda t: (
                    (t[3], (t[2], t[0], t[1], t[4])),
                    (t[4], (t[2], t[1], t[0], t[3])),
                )
            )
            chosen = candidates.reduceByKey(min_choice).collect()
            if not chosen:
                break

            comp_link_best = {}
            for comp_a, (w, u, v, comp_b) in chosen:
                if comp_a == comp_b:
                    continue
                ca, cb = (comp_a, comp_b) if comp_a <= comp_b else (comp_b, comp_a)
                eu, ev = (u, v) if u <= v else (v, u)
                cand = (w, eu, ev)
                prev = comp_link_best.get((ca, cb))
                if prev is None or cand < prev:
                    comp_link_best[(ca, cb)] = cand

            round_uf = UnionFind()
            merge_pairs = []
            mst_round = {}
            for (ca, cb), (w, u, v) in sorted(
                comp_link_best.items(), key=lambda item: (item[1][0], item[1][1], item[1][2])
            ):
                if round_uf.find(ca) == round_uf.find(cb):
                    continue
                round_uf.union(ca, cb)
                merge_pairs.append((ca, cb))
                mst_round[norm_edge(u, v, w)] = (u, v, w)

            if not merge_pairs:
                break

            mst_acc.extend(mst_round.values())

            merge_pairs_rdd = sc.parallelize(merge_pairs)
            components.unpersist()
            components = relabel_components_distributed(
                comp_by_v,
                merge_pairs_rdd,
                max_iterations=50,
            ).cache()
            components.count()
            iters += 1

        num_comp = components.values().distinct().count()
    finally:
        edges.unpersist()
        vertices.unpersist()
        components.unpersist()

    seen = set()
    unique_mst = []
    tw = 0
    for u, v, w in mst_acc:
        k = norm_edge(u, v, w)
        if k not in seen:
            seen.add(k)
            unique_mst.append(k)
            tw += k[2]

    return BoruvkaResult(
        mst_edges=sorted(unique_mst),
        total_weight=tw,
        num_iterations=iters,
        num_components=num_comp,
    )


# Run on a manageable graph for notebook validation
dist_path = PROJ_ROOT / "data" / "complex_random.txt"
dist_edges = load_graph_from_text(dist_path.read_text(encoding="utf-8"), fmt="edge_list")
res_dist = boruvka_mst_distributed_relabel(sc, sc.parallelize(dist_edges), max_iterations=200)
print_result_summary("§7 distributed-relabel", res_dist)
validate_vs_kruskal(
    res_dist,
    edges=dist_edges,
    name="§7 distributed-relabel vs kruskal",
    atol=1e-6,
)
pd.DataFrame(res_dist.mst_edges, columns=["u", "v", "weight"]).head(10)

ERROR:root:KeyboardInterrupt while sending command.           (1480 + 8) / 3080]
Traceback (most recent call last):
  File "/Users/kentpun/Documents/_04.studies/MSc BDT/MSBD 5003/_05. Project/Implementation/.venv/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kentpun/Documents/_04.studies/MSc BDT/MSBD 5003/_05. Project/Implementation/.venv/lib/python3.12/site-packages/py4j/clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

## 8. Stop Spark

Run this when you are done so JVM processes exit cleanly (especially if you re-run earlier sections often).

In [7]:
spark.stop()
print("Spark stopped.")

Spark stopped.